# GitHub Action for generating a contribution graph with a snake eating your contributions
name: Generate Snake

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- ADD THIS LINE

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Generate a snake SVG
          outputs: |
            dist/github-contribution-grid-snake.svg 
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # The branch the action should deploy to.
          target_branch: output
          # The build folder the action should deploy.
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
